version: "3"

services:
  web:
    build: .
    volumes:
      - ./:/usr/src/
    working_dir: /usr/src/
    command: sh -c 'alembic merge heads && python -m src'
    networks:
      - app-network
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - database


  database:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    volumes:
      - ./home/local_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network
    ports:
      - "25432:5432"



networks:
    app-network:
      #external: true