"""Database creation

Revision ID: 0b338971e2a3
Revises: 
Create Date: 2023-11-20 15:58:26.872863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b338971e2a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    op.drop_table('rars')
    op.drop_table('genre')
    op.drop_table('cover')
    op.drop_table('publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('publisher_publisher_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('publisher_name', sa.CHAR(length=40), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='publisher_pkey')
    )
    op.create_table('cover',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('cover_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cover_type_pkey')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.SMALLINT(), server_default=sa.text("nextval('genre_genre_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=30), autoincrement=False, nullable=True)
    )
    op.create_table('rars',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.VARCHAR(length=3), autoincrement=False, nullable=True)
    )
    op.create_table('authors',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('authors_author_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fullname_author', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='authors_pkey')
    )
    # ### end Alembic commands ###
