"""update colown price in book

Revision ID: 17638a06106d
Revises: 9df5f4ee8114
Create Date: 2023-11-24 19:19:53.357305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17638a06106d'
down_revision: Union[str, None] = '9df5f4ee8114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'unit_price',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'unit_price',
               existing_type=sa.DECIMAL(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
