"""refactor relationship

Revision ID: c517e9defa57
Revises: e3e89f2f588c
Create Date: 2023-11-22 13:03:37.035789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c517e9defa57'
down_revision: Union[str, None] = 'e3e89f2f588c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname_author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fullname_author')
    )
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    op.create_table('cover',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cover_type')
    )
    op.create_index(op.f('ix_cover_id'), 'cover', ['id'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre')
    )
    op.create_index(op.f('ix_genre_id'), 'genre', ['id'], unique=False)
    op.create_table('publisher',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('publisher_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publisher_name')
    )
    op.create_index(op.f('ix_publisher_id'), 'publisher', ['id'], unique=False)
    op.create_table('rars',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('rating', sa.VARCHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating')
    )
    op.create_index(op.f('ix_rars_id'), 'rars', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('book',
    sa.Column('ISBN', sa.VARCHAR(length=17), nullable=False),
    sa.Column('name_book', sa.VARCHAR(length=50), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.SMALLINT(), nullable=False),
    sa.Column('publisher_id', sa.SMALLINT(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('book_circulation', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('rars_id', sa.SMALLINT(), nullable=False),
    sa.Column('number_of_pages', sa.Integer(), nullable=False),
    sa.Column('cover_type_id', sa.Integer(), nullable=False),
    sa.Column('amount_book', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cover_type_id'], ['cover.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rars_id'], ['rars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ISBN')
    )
    op.create_index(op.f('ix_book_name_book'), 'book', ['name_book'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.VARCHAR(length=17), nullable=False),
    sa.Column('amount_item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.ISBN'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_id'), 'purchase', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_id'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_book_name_book'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rars_id'), table_name='rars')
    op.drop_table('rars')
    op.drop_index(op.f('ix_publisher_id'), table_name='publisher')
    op.drop_table('publisher')
    op.drop_index(op.f('ix_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_cover_id'), table_name='cover')
    op.drop_table('cover')
    op.drop_index(op.f('ix_author_id'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
